from __future__ import annotations

import datetime as dt
import pathlib
import textwrap

from cs_tools.updater import _bootstrapper
from mkdocs.config.defaults import MkDocsConfig
import cs_tools


def on_post_build(config: MkDocsConfig, **_options) -> None:
    """Copy the Bootstrapper to the base directory for a one-command installer."""
    site_dir = pathlib.Path(config["site_dir"])

    SRC_BOOT_PY = pathlib.Path(_bootstrapper.__file__)
    TAR_BOOT_PY = site_dir.joinpath("install.py")

    GENERATED_MESSAGE = textwrap.dedent(f"""
    # THIS FILE WAS GENERATED BY THE CS TOOLS DOCUMENTATION AT THE TIME OF DEPLOYMENT.
    # YOU CAN FIND THE ORIGINAL AT :: https://github.com/thoughtspot/cs_tools/blob/master/cs_tools/updater/_bootstrapper.py
    #
    # WHEN: {dt.datetime.now(tz=dt.timezone.utc).isoformat()}
    # VERS: v{cs_tools.__project__.__version__}
    #
    """)

    TAR_BOOT_PY.write_text(GENERATED_MESSAGE + SRC_BOOT_PY.read_text())
