from __future__ import annotations

import datetime as dt
import pathlib
import textwrap

from cs_tools.updater import _bootstrapper
from mkdocs.config.defaults import MkDocsConfig
import cs_tools


def on_post_build(config: MkDocsConfig) -> None:
    """
    Use this event to call post-build scripts.

    Copy the CS Tools Bootstrapper to the base directory for a one-command installer.

    Further reading:
      https://www.mkdocs.org/dev-guide/plugins/#on_post_build
    """
    site_dir = pathlib.Path(config["site_dir"])

    SRC_BOOT_PY = pathlib.Path(_bootstrapper.__file__)

    # DEV NOTE: @boonhapus, 2025/02/21
    #   WE PUT THIS AT THE BASE_DIR BECAUSE THE BOOTSTRAPPER SCRIPT IS RUN FROM curl OR
    #   powershell AND BOTH DON'T NATIVELY SUPPORT FOLLOWING JAVASCRIPT-BASED REDIRECTS
    #   (which is how mkdocs-redirect plugin implements an HTTP 301 / 307).
    #
    #   And we want to be vain and offer a link like https://thoughtspot.github.io/cs_tools/install.py :)
    #
    TAR_BOOT_PY = site_dir / "install.py"

    GENERATED_MESSAGE = textwrap.dedent(f"""
    # THIS FILE WAS GENERATED BY THE CS TOOLS DOCUMENTATION AT THE TIME OF DEPLOYMENT.
    # YOU CAN FIND THE ORIGINAL AT :: https://github.com/thoughtspot/cs_tools/blob/master/cs_tools/updater/_bootstrapper.py
    #
    # WHEN: {dt.datetime.now(tz=dt.timezone.utc).isoformat()}
    # VERS: v{cs_tools.__project__.__version__}
    #
    """)

    TAR_BOOT_PY.write_text(GENERATED_MESSAGE + SRC_BOOT_PY.read_text())
