__version__ = "1.5.9b5"
__docs__ = "https://thoughtspot.github.io/cs_tools/"
__repo__ = "https://github.com/thoughtspot/cs_tools"
__help__ = f"{__repo__}/discussions/"
__bugs__ = f"{__repo__}/issues/new/choose/"
