name: "ðŸ› Bug Report"
description: Found something wrong with cs_tools? Report it here.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: >-
        ## *Thanks for your interest in cs_tools!* :tada:

        While this project is maintained by the customer team at __ThoughtSpot__, it is our passion project!

        If you are experiencing an issue with your ThoughtSpot cluster, please open a [__Support Case__](https://community.thoughtspot.com/s/article/How-to-submit-a-ThoughtSpot-Support-Case).

        If you wish you had a feature in ThoughtSpot, please open a [__Product Idea__](https://community.thoughtspot.com/s/ideas).

  - type: checkboxes
    id: checks
    attributes:
      label: First Stop
      description: Please confirm and check all the following options.
      options:
        - label: I have read and agreed to the ThoughtSpot LICENSE.
          required: true

        - label: >-
            I understand that if I have a critical issue with __ThoughtSpot__, I should reach out to my designated __Account Executive__ and __Customer Success Manager__ instead of `cs_tools`.
          required: true

  - type: textarea
    id: platform-configuration
    attributes:
      label: Platform Configuration
      description: Please include the output of `cs_tools self info --anonymous --directory .`.
      placeholder: Drag the `cs-tools-info-YYYY-mm-dd.svg` into this window.

    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        What is the problem, question, or error?

        Write a short description telling us what you are doing, what you expect to happen, and what is currently happening.

        If we can copy it, run it, and see it right away, there's a much higher chance we'll be able to help you.

    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Considering adding a log file.
      description: >-
        Run the following command.

        `cs_tools logs report --latest 3`

        > !! Logs are not totally anonymous !!

        While logs should not hold any secrets, they can still contain information that you may not want publicly
        available. We can provide a secure mechanism to share logs if this is required.
